Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1016, in _execute
    self.prepare()
  File "/var/www/blog/BaseHandler.py", line 54, in prepare
    self.cursor.execute(sql)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')